### ISSUE TITLE
custom items are confusing

### ISSUE THREAD

**Issue by Vosjedev** [GeyserMC/GeyserWiki#100]
hi  
I am looking at [this](https://wiki.geysermc.org/geyser/custom-items/) page, and i am very confused on how to do this. is it like:  
```
{
    "format_version": 1,
    "items": {
        "minecraft:black_stained_glass_pane": [
            {
                "name": "item_1"
                "custom_model_data": "123456"
                "name": "item_2"
                "custom_model_data": "987654"
            }
        ]
    }
}
```
or
```
{
    "format_version": 1,
    "items": {
        "minecraft:black_stained_glass_pane": [
            {
                "name": "item_1" {
                                "custom_model_data": "123456"
                }
                "name": "item_2" {
                                "custom_model_data": "987654"
                }
            }
        ]
    }
}
```
or something completely different?   
I would like some more information. maybe some examples, or a zip with an editable preset (the geyser json + the bedrock pack)

thanks!

**Comment by onebeastchris** [comment]
I'd recommend to ask that in the GeyserMC discord (discord.gg/GeyserMC), there's a dedicated channel to resource pack questions. But yea, wiki ain't easy to read, but that's due to the complexity of the feature.
