### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by PixelcrafterEXE** [GeyserMC/GeyserWiki#107]
A wiki page for setting up a standalone server as a container would be pretty useful.

**Comment by onebeastchris** [comment]
What would you want to get added exactly? You'd set up a docker container with your minecraft server, but add a rule for 19132 on UDP in the config.
Also, there's this https://github.com/GeyserMC/pterodactyl-stuff

**Comment by Chew** [comment]
> You'd set up a docker container with your minecraft server, but add a rule for 19132 on UDP in the config.

How do you do this? There's your article

**Comment by onebeastchris** [comment]
This is available on the wiki now:
https://wiki.geysermc.org/geyser/port-forwarding/#using-docker-or-pterodactyl
