### ISSUE TITLE
Spartan AntiCheat

### ISSUE THREAD

**Issue by Vagdedes** [GeyserMC/GeyserWiki#122]
In regards to:
https://wiki.geysermc.org/geyser/anticheat-compatibility/

Bedrock support is provided in the original purchase of Spartan since 4th of January 2023. Additionally, it is a full compatibility by not ignoring and checking the bedrock players. Would appreciate if you could correct its description and move it to the "Full Compatibility" list.

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/GeyserWiki/blob/master/_docs/geyser/anticheat-compatibility.md
Feel free to submit a PR with the changes you'd want to make, I've linked the page above

**Comment by Vagdedes** [comment]
Thanks. There you go:
https://github.com/GeyserMC/GeyserWiki/compare/master...Vagdedes:GeyserWiki:patch-1

**Comment by onebeastchris** [comment]
That's a commit to your own fork, could you open a PR from your fork to the Geyser-Wiki repo now? That would allow us to actually merge it after review :-)
