### ISSUE TITLE
link java to bedrock 

### ISSUE THREAD

**Issue by DeffStrife** [GeyserMC/GeyserWiki#124]
my bedrock account is main so I want to link java to bedrock. but linking server won't me to do that

**Comment by onebeastchris** [comment]
This is the Geyser wiki, you'd want to request this over at the Floodgate Repository.

And that isn't an option - however, if you transfer all your items/ender chest contents etc to java before linking, you'll effectively have everything on both accounts. There is no option to join as the bedrock username when linked though, the java one will be used.

**Comment by Camotoy** [comment]
The linking server also needs updated to 1.19.60 which we will attempt to do soon.
