### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by daddfddf** [GeyserMC/GeyserWiki#13]
[13:12:16 ERROR]: Could not load 'plugins/floodgate-spigot.jar' in folder 'plugins

**Comment by Jens-Co** [comment]
Hello, 

Can you please add the full server logs ( Latest.log ) on your issue? You can upload them with this; ( https://mclo.gs )
Without additional info we cannot do much.

Thanks!

**Comment by Konicai** [comment]
This is our GitHub repo for the wiki, not for Geyser itself. 

You're also better off getting help on our Discord, you're likely just experiencing user error. https://discord.gg/GeyserMC
