### ISSUE TITLE
Question:My paper minecraft server

### ISSUE THREAD

**Issue by SlugLaz** [GeyserMC/GeyserWiki#135]
Question on: https://github.com/GeyserMC/GeyserWiki/tree/master/_docs/floodgate/issues.md
My paper server work but some reason my java client can log in to the server but not my bedrock client

**Comment by onebeastchris** [comment]
This is a question better suited for Geyser's support discord - or, if you want to give it a shot yourself, refer to these written guides:

https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/
https://wiki.geysermc.org/geyser/common-issues/

**Comment by SlugLaz** [comment]
> This is a question better suited for Geyser's support discord - or, if you want to give it a shot yourself, refer to these written guides:
> 
> https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/ https://wiki.geysermc.org/geyser/common-issues/

I put localhost does that still mean I need to port forward
