### ISSUE TITLE
Force texture packs

### ISSUE THREAD

**Issue by Lemon4ik6484** [GeyserMC/GeyserWiki#147]
in config i found "force-resource-packs" is it force players to load bedrock or java resource pack, and if bedrock, how to set it? (english is not my native language, so sorry if i said something wierd)

**Comment by onebeastchris** [comment]
enabling that config option forces bedrock players to accept & load the bedrock packs that you have to manually add in Geyser's packs folder - see https://wiki.geysermc.org/geyser/faq/#how-can-i-have-bedrock-players-load-resource-packs for more info.
