### ISSUE TITLE
GeyserConnect changes

### ISSUE THREAD

**Issue by j-romchain** [GeyserMC/GeyserWiki#151]
There seems to have recently been a major change in how to use GeyserConnect. The entire page on the program likely needs updating.

**Comment by rtm516** [comment]
This has been done as of https://github.com/GeyserMC/GeyserWiki/commit/1879951ffd356d52e0c0ce6fe78ab63d6f3a122c and https://github.com/GeyserMC/GeyserWiki/commit/5456c0d2d1176c2616fdac7e75701d6638f99c2f
