### ISSUE TITLE
Question: Bedrock players do not load the world when they enter the game

### ISSUE THREAD

**Issue by KANTNOLI** [GeyserMC/GeyserWiki#169]
I have the following problem! Bedrock players do not load the world when they enter the game. Couldn't find any info on how to fix it. After restarting the server, this bug disappears for 2 minutes 30 seconds on average. If the player was on the server after the restart, then everything just froze for him, but at the same time, for Java, he could visually move like a star, and also hit through the walls! I really need your help! I apologize for my language, I use a translator.

**Comment by onebeastchris** [comment]
This is the Geyser wiki github repository; not GeyserMC/Geyser.
Furtermore; your bug sounds like https://github.com/geyserMC/geyser/issues/2861
