### ISSUE TITLE
Question: (this was fine last month) what should i do?

### ISSUE THREAD

**Issue by TrexGmaerYT** [GeyserMC/GeyserWiki#192]
Question on: pages/index.md
I'm using GeyserMC to play on a crossplay world but i can see custom java skins but bedrock skins are one of the new default minecraft skins/avatars.

**Comment by rtm516** [comment]
This isnt a Wiki issue, it was a global api/geyser/floodgate issue. It should be resolved. If not open an issue on the main Geyser repo
