### ISSUE TITLE
Question: GPortal

### ISSUE THREAD

**Issue by SonnenPingu** [GeyserMC/GeyserWiki#209]
Question on: _docs/geyser/supported-hosting-providers.md

Need to contact support to open a UDP port, then use that as the bedrock port in the config. Also, uncomment bedrock address and make sure it is set to your Java server IP. 
^^^^^^^^^^^^
Unfortunately, this is not correct. One does not need the support for the port.

You do not have to address the support.
Each MC server has 4 ports free after its query port.
So if you have 34565 as query port. You can use 34566 for Geyser or 34570 for Geyser.
The IP address must always be entered, because the GameClouds of GPORTAL do not allow to bind to 0.0.0.0. 

Your Quert port will always follow the scheme XXX65. The additional free ports are XXX66 - XXX70 respectively.

You can use these open ports for your mods, PlugIns, etc.. ... use.
 Found on: https://www.g-portal.com/wiki/en/what-ports-can-i-use-for-minecraft-mods-and-plugins-that-require-an-extra-port/

**Comment by onebeastchris** [comment]
Hey, feel free to make a PR to this file (https://github.com/GeyserMC/GeyserWiki/blob/master/_data/providers.json) to adjust the GPortal entry :)

**Comment by SonnenPingu** [comment]
Closed by #210
