### ISSUE TITLE
Question:Unable to initialise query system on 0.0.0.0:25565

### ISSUE THREAD

**Issue by RenegadeKyle** [GeyserMC/GeyserWiki#216]
Question on: pages/search.html 
I have copied the IP exactly on both bedrock and remote Section of my config file and im getting the same error. im using server,pro and all the ports and IP's match what im given. the server starts up with that everytime and i cant figure out how to change it.

**Comment by Konicai** [comment]
Disable query in server.properties

For further questions, please ask on our Discord
