### ISSUE TITLE
Question: bad Maven URL

### ISSUE THREAD

**Issue by maguro027** [GeyserMC/GeyserWiki#219]
Question on: _docs/geyser/getting-started-with-the-api.md

original

<repository>
    <id>opencollab-snapshot</id>
    <url>https://repo.opencollab.dev/main/</url>
</repository>

i think 

<repository>
<id>opencollab-snapshot</id>
<url>https://repo.opencollab.dev/maven-snapshots/</url>
</repository>

**Comment by onebeastchris** [comment]
`https://repo.opencollab.dev/main/` contains both `https://repo.opencollab.dev/maven-snapshots` and `https://repo.opencollab.dev/maven-releases` - some dependencies are only available as a snapshot, some only as a release, so having a link that contains both makes it simpler.
