### ISSUE TITLE
Can not unlink my account

### ISSUE THREAD

**Issue by s4sutler100** [GeyserMC/GeyserWiki#240]
Can not unlink my account I would like help?

**Comment by onebeastchris** [comment]
Join the `link.geysermc.org` server on either java or bedrock, and run `/unlinkaccount` there.

**Comment by s4sutler100** [comment]
i tried that and some reason it hiccupped

**Comment by onebeastchris** [comment]
Could you describe said "hiccup" in more detail?
As in, were you unable to join the linking server, or did the command not work, or did it say that you unlinked but you still joined as a linked player?

In the last case, you'd need to either wait a while for it to unlink, or restart the server that you're joining.
