### ISSUE TITLE
Question: Floodgate branch "Master" not available on ci.opencollab.dev

### ISSUE THREAD

**Issue by NiiWiiCamo** [GeyserMC/GeyserWiki#249]
Question on: _docs/floodgate/linking.md

Where can I download the floodgate-sqlite-database.jar file to enable local linking?

This link is dead, the master branch is not on there.
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/

**Comment by Tim203** [comment]
Duplicate of #248
