### ISSUE TITLE
Question: may i ask how to use this, i want to get rid of the "showscoreboardlogs", its very annoying and its making the logs very long

### ISSUE THREAD

**Issue by Keinini** [GeyserMC/GeyserWiki#252]
Question on: _docs/geyser/geyser-command-line-arguments-and-system-properties.md

**Comment by onebeastchris** [comment]
Those are java system properties, so you'd have to add them to your server startup command.
For example: 
`java -jar paper.jar --nogui` would turn to `java -DGeyser.ShowScoreboardLogs=true -jar paper.jar --nogui`.
