### ISSUE TITLE
Outdated client. Please use 1.21

### ISSUE THREAD

**Issue by Egriffith8368** [GeyserMC/GeyserWiki#281]
I am using Geyser for Minecraft server and every time a xbox player attempts to join it throws a  Kicked whilst connecting to hub error: Outdated client. It says to use 1.21 but I am and so are all of the servers. How ight i fix this problem. The server works fine on java edition but the second someone on bedrock try's to join the same error keeps happening.
![Screenshot 2024-06-14 at 12 41 57 PM](https://github.com/GeyserMC/GeyserWiki/assets/125297215/b5731a5d-bd70-4558-82f4-4cf58e40461d)

**Comment by Camotoy** [comment]
Please use these builds for now: https://github.com/GeyserMC/Geyser/pull/4740
