### ISSUE TITLE
Question: inventory didnt link

### ISSUE THREAD

**Issue by pesomaxd** [GeyserMC/GeyserWiki#291]
Question on: _docs/floodgate/linking.md
i linked my bedrock account to my java account and the items that i have on my java account didnt link to the bedrock account, how can i fix this? 
![Screenshot 2024-07-07 052158](https://github.com/GeyserMC/GeyserWiki/assets/100422823/17f2bd2c-ca4b-4b7c-b715-53a2414cab8e)
![image](https://github.com/GeyserMC/GeyserWiki/assets/100422823/970698fd-1e96-4f20-84ea-7397d8c33b11)

**Comment by Konicai** [comment]
Please join our Discord server for support
