### ISSUE TITLE
It doesn't tell me how to unlink accounts from floodgate

### ISSUE THREAD

**Issue by zap8600** [GeyserMC/GeyserWiki#52]
I'm in an SMP that uses Geyser and Floodgate, and I linked my Java and Bedrock accounts. Unfortunately,  all my stuff was on my Bedrock account. Running `/unlinkaccount` just gives me a link to the linking website. Give information on how to use the commands please.

**Comment by Chew** [comment]
If it gives a link to the website, the server probably uses global linking. `/unlinkaccount` is only if the server uses local linking. Use the website to unlink.

Since this isn't clear, will leave open to hopefully improve it.

**Comment by zap8600** [comment]
How do I unlink with the website? It doesn't say where to unlink.

**Comment by Konicai** [comment]
Read this to unlink: https://link.geysermc.org/method/server
