### ISSUE TITLE
Add more info to forms and cumulus

### ISSUE THREAD

**Issue by Vilatik** [GeyserMC/GeyserWiki#67]
Hello! Please add more information about forms and cumulus. Like examples or full code. How to get uuid from nickname. I couldn't find how get uuid from nickname

**Comment by Tim203** [comment]
Cumulus is our form API. For information about the Floodgate API you can either look at the code or at [the wiki about the Floodgate API](https://wiki.geysermc.org/floodgate/api/).

**Comment by Vilatik** [comment]
Yes, i know. But on wiki no information about getting uuid of floodgate player

**Comment by Vilatik** [comment]
This code not workink too.
These uuid specialy give geyser player. Its not default uuid from bukkit
