### ISSUE TITLE
Question: How do you enable the Optional Pack server-side?

### ISSUE THREAD

**Issue by JimmJam** [GeyserMC/GeyserWiki#73]
Question on: https://github.com/GeyserMC/GeyserWiki/tree/master/_docs/other/geyseroptionalpack.md

The documentation says it is recommended to install the optional pack server side, but can be installed client side as well. I frequently connect from my Switch where it is nigh impossible to download packs, so is it possible to enable packs server side in the Geyser config?

**Comment by Camotoy** [comment]
Geyser has an option to allow server resource packs by placing them in the `packs` folder wherever the Geyser config is located.

**Comment by JimmJam** [comment]
Oh - does it have to be in .mcpack format or unzipped? I can't seem to get it to work with either. (Thank you for the (very!) quick response !)

**Comment by Camotoy** [comment]
.mcpack and .zip should both work.

**Comment by JimmJam** [comment]
Thank you! I'll do my own work this end until it works.

**Comment by onebeastchris** [comment]
can be closed ig
