### ISSUE TITLE
Nintendo Switch user error message "server requires a paid Java account" 

### ISSUE THREAD

**Issue by AgentStridor** [GeyserMC/GeyserWiki#77]
Question on: https://github.com/GeyserMC/GeyserWiki/tree/master/_docs/floodgate/root.md

I have several Switch Bedrock players trying to join my Java server. After jumping through several hoops, the final hoop is this error message "server requires a paid Java account".  Is there a setting somewhere in the geyser or floodgate plugin that I'm missing to bypass this?

**Comment by Camotoy** [comment]
You either don't have Floodgate installed, or you're connecting to the wrong server.

**Comment by onebeastchris** [comment]
Did you set "auth-type" in geyser's config.yml to "floodgate"?

**Comment by AgentStridor** [comment]
I set it to floodgate in geyser's config.

**Comment by AgentStridor** [comment]
There is a video on apex how to set up geyser. Followed it to a T. https://apexminecrafthosting.com/geysermc/ 
walked players through this path...
geyserconnect.net
port: 19132
Add server list selected.
then added my IP with Port 8.8.8.8 or if that doesn't work 1.1.1.1

**Comment by Camotoy** [comment]
That sounds like the Switch users are joining a "Java server" in GeyserConnect when they should be joining a "Bedrock/Geyser server" when GeyserConnect prompts them.

**Comment by AgentStridor** [comment]
I just figured out what might have been the problem.  The config.yml might have had a typo.  in the config.yml file i called the file 'public-key.pem' but its actually 'key.pem'

**Comment by AgentStridor** [comment]
We got them in!  It was so complicated but it works now!  First, I had the wrong port.  Not the 8.8.8.8 but our personal port was reverting back to an old bedrock port that wasn't working and would give the error that they couldn't join world.  Then errors of couldn't be whitelisted.  I had to actually whitelist using fwhitelist add UUID instead of fwhitelist add .username.  People were getting into the java server but blocks weren't loading and they couldn't move or type in commands.  Then we stumbled on this link and fixed the parameters.   It was an encryption bug so you have to tell it not to encrypt. https://github.com/GeyserMC/Geyser/issues/2861
Hopefully this helps others with this issue.

**Comment by iamsomecow** [comment]
.
